### ISSUE TITLE
`carma` changes install location based on installation status

### ISSUE THREAD

**Issue by TNonet** [RUrlus/carma#108]
Hi @RUrlus,

As a follow-up to this comment, https://github.com/RUrlus/carma/issues/103#issuecomment-1133958194, I believe I have found other questions/issues that I wanted to raise.

I have observed when using `scikit build` and `carma` to install a C++ extension library, depending on if I have included `carma` as a subdirectory vs. have already installed `carma`, the installation location of the python package changes.

When building wheels for a python package with `carma` as a subdirectory, the setup process tries to install files outside the project root.  An example build can be found here: https://github.com/TNonet/carma-py-example/actions/runs/2367595957.

```
   [100%] Built target carma_py_example
    Install the project...
    -- Install configuration: "Release"
    -- Installing: /usr/local/./carma_py_example.cpython-36m-darwin.so
    CMake Error at cmake_install.cmake:51 (file):
      file INSTALL cannot copy file
      "/Users/runner/work/carma-py-example/carma-py-example/_skbuild/macosx-10.9-x86_64-3.6/cmake-build/carma_py_example.cpython-36m-darwin.so"
      to "/usr/local/./carma_py_example.cpython-36m-darwin.so": Permission
      denied.
```

However, when `carma` is installed directly, this does not happen, and everything installs fine. An example build can be found here https://github.com/TNonet/carma-py-example/actions/runs/2367582605. 

The diff between these two commits can be found here: https://github.com/TNonet/carma-py-example/commit/f7abda3f0df6193412923ca31d5d831f0b83b1ae

**Comment by RUrlus** [comment]
Hi @TNonet,

I think I found it, there was an unset `CMAKE_INSTALL_PREFIX` hiding in one of the CMake modules.
Can you try latest stable?

**Comment by TNonet** [comment]
Hi @RUrlus,

That seems to have worked. I will close this issue.

Thanks

**Comment by RUrlus** [comment]
Good, I completely forgot about clearing the cmake cache when I first read the issue. Happy it's found and solved
