### ISSUE TITLE
Segmentation Fault on Carma Example code

### ISSUE THREAD

**Issue by TNonet** [RUrlus/carma#109]
Hi @RUrlus,

Something seems wrong with the manual conversion logic of the Carma Example code. 

The code seems to work correctly for most Linux images but fails for cp36-manylinux_i686 CPython 3.6 manylinux i686

https://github.com/TNonet/carma-py-example/runs/6609546092?check_suite_focus=true.

**Comment by TNonet** [comment]
I am seeing similar issues with my original project `L0Learn`. This code has been tested significantly so I suspect the issue is from `carma` as well.

https://github.com/TNonet/L0Learn/runs/6625390002?check_suite_focus=true

**Comment by RUrlus** [comment]
Hi @TNonet,

I am going to need a bit more info to go on as the above links don't show the portion of the logs where an error is reported.
As Python 3.6 is well past end-of-life, which in combination with i686 being a known troublesome architecture doesn't make me super keen on making changes for this very specific case. If there is an issue for other archs that is a different case

**Comment by TNonet** [comment]
Hi @RUrlus,

That is fair. I will close this for now and potentially reopen it later if I locate the issue.
