### ISSUE TITLE
Is there a way to use carma from source?

### ISSUE THREAD

**Issue by dcajasn** [RUrlus/carma#115]
I'm working on new functions for my library [Riskfolio-Lib](https://github.com/dcajasn/Riskfolio-Lib) that are based on armadillo. My first attempt was to use [arma_numpy](https://github.com/LiamPattinson/arma_numpy), it works well on Mac and Linux but it failed on windows ☹️. Now I found your library that looks very friendly, however when I tried to reproduce the example using setuptools instead of CMake on M1 Mac, it gives me the following error: 

> ImportError: dlopen(/Users/dany/Desktop/cursoc/risker/examples/example_carma.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '__Z17bind_exampleclassRN8pybind117module_E

My setup.py file is:

```
#!/usr/bin/env python
import os
import sys
from glob import glob

import pybind11
from pybind11 import get_cmake_dir
from pybind11.setup_helpers import Pybind11Extension, build_ext
from setuptools import setup

import numpy as np

# Obtain the numpy include directory.  This logic works across numpy versions.
try:
    numpy_include = np.get_include()
except AttributeError:
    numpy_include = np.get_numpy_include()

armadillo_path = os.path.abspath('../functions3/external/armadillo/include')
carma_path = os.path.abspath('../functions3/external/carma/include')

__version__ = '0.1'

external_module = [
    Pybind11Extension("example_carma",
        sources=['example_bindings.cpp',
                ],
        include_dirs = [numpy_include, armadillo_path, carma_path, pybind11.get_include()],
        define_macros = [('VERSION_INFO', __version__)],
        ),
]

setup (name = 'example_carma',
version = __version__,
author = "Dany",
description = """Setuptools carma test""",
cmdclass={"build_ext": build_ext},
zip_safe = False,
ext_modules = external_module,
)
```

**Comment by RUrlus** [comment]
Hi @dcajasn, `__Z17bind_exampleclassRN8pybind117module_E` is not necessarily carma related. It's most likely an issue with the pybind11 binding code/setup not working correctly. Can you verify that?

If it's carma related we certainly need more information. Carma can certainly be used header only without cmake but you have to make sure that the include order is correct. carma needs to be included before armadillo

**Comment by dcajasn** [comment]
Thanks for your response @RUrlus, I've finally find a way to solve the problem on Mac and Windows, however now I have a new problem, when I try to multiply two matrixes on windows I have the following error:

> ImportError: DLL load failed while importing func_example: The specified module could not be found.

My function is:

```
py::array_t<double> kurtosis_matrix(const py::array_t<double> & arr) {
    arma::Mat<double> Y = carma::arr_to_mat<double>(arr);
    double T = Y.n_rows;
    double N = Y.n_cols;
    arma::Mat<double> mu = arma::mean(Y);
    arma::Mat<double> mu_mat(arma::size(Y), fill::zeros);
    mu_mat.each_row() = mu; 
    arma::Mat<double> X = Y - mu_mat;
    arma::Mat<double> ones(1, X.n_cols, fill::ones);
    arma::Mat<double> K = arma::kron(ones, X) % arma::kron(X, ones);
    \\ I don't have errors if I comment the matrix multiplication
    K = 1/T * K.t() * K;
    return carma::mat_to_arr<double>(K);
}
```
Do you have any idea why is this happening ?, when I multiply two sparse matrixes on windows I don't have this problem.

**Comment by RUrlus** [comment]
This sounds like a linking issue with BLAS/LAPACK which is typically not used for sparse matrices. CARMA does not link to BLAS/LAPACK and Armadillo might depending on how you set it up.

A good place to start would be verifying whether BLAS is being linked properly on Windows

**Comment by RUrlus** [comment]
@dcajasn Any success on the matter? Without any indication that this is a Carma issue I will be closing the issue

**Comment by dcajasn** [comment]
Hi @RUrlus, yes, it is a linking issue with BLAS/LAPACK. Thanks for your work, carma is an amazing project.
