### ISSUE TITLE
CARMA does not correctly borrow the array when used with pybind11 trampoline classes, resulting in referencing garbage collected memory

### ISSUE THREAD

**Issue by dzuev2** [RUrlus/carma#118]
When using pybind11 trampoline classes (https://pybind11.readthedocs.io/en/stable/advanced/classes.html#overriding-virtual-functions-in-python) for overriding c++ virtual functions CARMA fails to properly borrow the numpy array memory. Simple repro:

armatrampoline.h
```
#include <armadillo>
#include <carma>
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>


void bind_armaloader(py::module &m);
```

armatrampoline.cpp
```
#include "armatrampoline.h"

namespace py = pybind11;

/*
 * Trampoline class which the Python classes (ultimately) inherit from
 *
 * See https://pybind11.readthedocs.io/en/stable/advanced/classes.html
 */

class ArmaDataLoader
{
public:
    virtual ~ArmaDataLoader() = default;

    virtual arma::Col<double> getVector(int length) = 0;
};

class PyArmaDataLoader : public ArmaDataLoader
{
public:
    using ArmaDataLoader::ArmaDataLoader;

    arma::Col<double> getVector(int length) override
    {
        PYBIND11_OVERRIDE_PURE_NAME(arma::Col<double>, ArmaDataLoader, "get_vector", getVector, length);
    }
};

void call_arma_vec(ArmaDataLoader* loader) {
    assert(loader!=nullptr);

    constexpr int LEN = 1000;
    const arma::Col<double> ret = loader->getVector(LEN);

    if(ret.n_elem != LEN) {
      throw("Incorrect size of the output array");
    }

    for(int i = 0; i < LEN; ++i) {
      if(fabs(ret[i] - double(i)) > 1e-5) {
        std::stringstream err;
        err << "Mismatching element expected " << i << " got " << ret[i] << "\n";
        std::cout << "TEST FAILURE: " << err.str() << std::endl;
        throw(err.str());
      }
    }

    std::cout << "All elements match!" << std::endl;

    return;
}

void bind_armaloader(py::module &m) {
    py::class_<ArmaDataLoader, PyArmaDataLoader /* <--- trampoline*/>(m, "ArmaDataLoader")
        .def(py::init<>())
        .def("get_vector", &ArmaDataLoader::getVector);

    m.def("call_arma_vec", &call_arma_vec);
}
```

carma_examples.py:
```
import numpy as np

import example_carma as carma

class SimpleLoader(carma.ArmaDataLoader):
    def __init__(self):
        super().__init__()

    def get_vector(self, len):
        return np.array([i for i in range(len)])


simple_loader = SimpleLoader()
carma.call_arma_vec(simple_loader)
```

Running the code above result in arma::Col<double> vector referencing garbage collected memory:
```
python carma_examples.py
TEST FAILURE: Mismatching element expected 1 got 9.45313e+218
```

We managed to write a workaround by providing type_caster specialization for arma::Col<double> and modifying load() method to force to always copy input np array:
```
        /* Convert numpy array to Armadillo Matrix. We override default behavior of carma to always copy. */
        bool load(handle src, bool)
        {
            // set as array buffer
            py::array_t<T> buffer = py::array_t<T>::ensure(src);
            if (!buffer)
            {
                throw carma::ConversionError("CARMA: Input cannot be interpreted as array.");
            }
            // copy the array
            arma::Col<double> tmp = carma::to_arma<arma::Col<double>>::from(buffer, true);
            // meet conditions that allow armadillo to steal the matrix
            arma::access::rw(tmp.n_alloc) = tmp.n_elem;
            arma::access::rw(tmp.mem_state) = 0;
            // move the created matrix into the empty but instantiated default
            value = std::move(tmp);
            return true;
        }
```

Workaround confirms the issue of referencing garbage collected memory. However, this solution is not ideal since:

- We need to override type_caster for all types (arma::Col<T>, arma::Mat<T> for T=double, int, etc) for all types used in trampoline classes

- The copying is forced for cases even outside of the trampoline class usage, where borrowing would have worked.

**Comment by RUrlus** [comment]
@dzuev2 This is not a bug. When borrowing, you are responsible for ensuring that the memory that is borrowed remains valid.

You should either manually increase/decrease the reference count of the object in question or copy in.
Rather than implementing a custom type_caster you can just take in a `py::array_t` and convert it using the manual converters for which you can set `copy=true`

```C++

template <typename T>
void foo(py::array_t<T>& src) {
     arma::Col<T> dst = carma::arr_to_col(src, true);
     ...
}
```

**Comment by dzuev2** [comment]
Thanks for the clarification. Regarding your suggestion on calling manual converters directly with copy=true, in the context of overriding classes I guess it implies we need to create our own version of the following pybind11 macro - https://github.com/pybind/pybind11/blob/00126859a550d10fb9f5bc0d4fdf86988c2012f4/include/pybind11/pybind11.h#L2771-L2784

Roughly:

```
template<typename T>
pybind11::array_t<T>
get_array_buffer(pybind11::handle src)
{
    pybind11::array_t<T> buffer = pybind11::array_t<T>::ensure(src);
    if (!buffer)
    {
        throw carma::ConversionError("CARMA: Input cannot be interpreted as array.");
    }
    return buffer;
}

#define PYBIND11_OVERRIDE_IMPL_ARMA_COPY(ret_type, cname, name, ...)                                                   \
    do                                                                                                                 \
    {                                                                                                                  \
        pybind11::gil_scoped_acquire gil;                                                                              \
        pybind11::function override = pybind11::get_override(static_cast<const cname *>(this), name);                  \
        if (override)                                                                                                  \
        {                                                                                                              \
            auto o = override(__VA_ARGS__);                                                                            \
            auto buffer = get_array_buffer<ret_type::elem_type>(o);                                                    \
            if (arma::is_Col<ret_type>::value)                                                                         \
            {                                                                                                          \
                return carma::arr_to_col(buffer, true);                                                                \
            }                                                                                                          \
            else if (arma::is_Mat<ret_type>::value)                                                                    \
            {                                                                                                          \
                return carma::arr_to_mat(buffer, true);                                                                \
            }                                                                                                          \
            else if (arma::is_Cube<ret_type>::value)                                                                   \
            {                                                                                                          \
                return carma::arr_to_cube(buffer, true);                                                               \
            }                                                                                                          \
            else                                                                                                       \
            {                                                                                                          \
                throw carma::ConversionError("Incorrect type - can only convert arma::Col, arma::Mat or arma::Cube."); \
            }                                                                                                          \
        }                                                                                                              \
    }                                                                                                                  \
    while (false)

#define PYBIND11_OVERRIDE_PURE_NAME_ARMA_COPY(ret_type, cname, name, fn, ...)                                       \
    do                                                                                                              \
    {                                                                                                               \
        PYBIND11_OVERRIDE_IMPL_ARMA_COPY(PYBIND11_TYPE(ret_type), PYBIND11_TYPE(cname), name, __VA_ARGS__);         \
        pybind11::pybind11_fail("Tried to call pure virtual function \"" PYBIND11_STRINGIFY(cname) "::" name "\""); \
    }                                                                                                               \
    while (false)
``` 

In theory this could work, but just wanted to note some complications here that now you also need to write some workaround code in case if you do not return directly the arma types, but lets say composite structure:

```
struct FooBar {
	arma::Col<double> double_col;
	arma::Col<int>	  int_col;
	arma::Mat<double> double_mat;
};
```

I am wondering though whether we can make carma type_caster recognize scenarios when memory can be safely borrowed vs when it has to be copied? I believe pybind11 Eigen::Ref (https://pybind11.readthedocs.io/en/stable/advanced/cast/eigen.html#pass-by-reference) implements somewhat similar logic where it can dynamically determine when to copy vs when to borrow.

**Comment by RUrlus** [comment]
```C++
if (arma::is_Col<ret_type>::value) {
     ....
```
is not needed as you can call 
```C++
carma::to_arma<ret_type>::from(buffer, true);
```

I am not familiar with trampoline classes or the required macro you linked above.
Regarding the Eigen::Ref we already do all of this, we check if compatible and try to covert if not.
Knowing whether the memory will be dereferenced during the lifetime of the arma object is certainly not possible.
If you want to give ownership of the Numpy array's memory to the armadillo object you should be passing it as an r-value.

I suggest having a look the following two sections in the documentation: [1](https://carma.readthedocs.io/en/latest/basic_usage.html#design-patterns), [2](https://carma.readthedocs.io/en/latest/carma.html#numpy-to-armadillo)

**Comment by dzuev2** [comment]
> is not needed as you can call
> carma::to_arma<ret_type>::from(buffer, true);

Thanks, that simplifies logic a lot, however still requires some additional handling for composite classes like FooBar I posted above.

> I am not familiar with trampoline classes or the required macro you linked above.

According to the official pybind11 documentation (https://pybind11.readthedocs.io/en/stable/advanced/classes.html#overriding-virtual-functions-in-python) trampoline classes is the way of overriding virtual functions in python with pybind11. Since CARMA:

>The library extends the impressive [pybind11](https://pybind11.readthedocs.io/en/stable/intro.html) library with support for Armadillo.

then it should probably handle this use case as well?

**Comment by RUrlus** [comment]
I do not plan to add specific functionality to handle trampoline classes, but I am happy to accept a contribution.

**Comment by RUrlus** [comment]
Did you try passing the array as an rvalue btw? This should trigger a different converter which takes ownership of the array from Numpy

**Comment by dzuev2** [comment]
Sounds good, in case if I come with a solution I will send the PR your way. Otherwise it seems like current workaround is to force copy by either overriding the caster as in 
https://github.com/RUrlus/carma/issues/118#issue-1610313876
or
https://github.com/RUrlus/carma/issues/118#issuecomment-1456461992

> Did you try passing the array as an rvalue btw? This should trigger a different converter which takes ownership of the array from Numpy

I am not sure how to do it since it will probably involve modifying some  of the PYBIND11_OVERRIDE_* macros. I will post an update if I figure out how to do that.
