### ISSUE TITLE
CMake Error _add_library cannot create target "armadillo" because an imported target   with the same name already exists

### ISSUE THREAD

**Issue by BerriJ** [RUrlus/carma#125]
Hi there,

First of all: I know this is not a bug of carma but rather my incapability to understand the mechanics of CMAKE.

I built a very small [boilerplate protect](https://github.com/BerriJ/carma_boilerplate) using `armadillo`, `pybind11` and `carma`.

I installed `carma` on my system using: 

```
git clone --depth=1 https://github.com/RUrlus/carma.git /usr/local/carma \
    && rm -rf /usr/local/carma/.git \
    && cd /usr/local/carma \
    && mkdir build \
    && cd build \
    && cmake -DCARMA_INSTALL_LIB=ON .. \
    && cmake --build . --config Release --target install \
    && rm -rf /usr/local/carma
```

For `pybind11` and `armadillo` I used vcpkg:

```
git clone --depth=1 https://github.com/Microsoft/vcpkg /usr/local/vcpkg \
    && rm -rf /usr/local/vcpkg/.git \
    && cd /usr/local/vcpkg \
    && ./bootstrap-vcpkg.sh \
    && ./vcpkg integrate install \
    && /usr/local/vcpkg/vcpkg install armadillo \
    && /usr/local/vcpkg/vcpkg install pybind11 \
    && chown --recursive $USERNAME:$USERNAME /usr/local/vcpkg

ENV PATH="/usr/local/vcpkg:${PATH}"
```
However, creating the build files fails:

```
$ cmake .. -DPYTHON_LIBRARY_DIR="/usr/local/lib/python3.10/dist-packages" -DPYTHON_EXECUTABLE="/usr/bin/python3.10"

-- Found pybind11: /usr/local/include (found version "2.11.1")

CMake Error at /usr/local/vcpkg/scripts/buildsystems/vcpkg.cmake:639 (_add_library):
  _add_library cannot create target "armadillo" because an imported target
  with the same name already exists.
Call Stack (most recent call first):
  /usr/local/share/carma/cmake/carmaDependencyTargets.cmake:34 (ADD_LIBRARY)
  /usr/local/share/carma/cmake/carmaConfig.cmake:89 (INCLUDE)
  /usr/local/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  CMakeLists.txt:34 (find_package)

-- Found carma: /usr/local/include/carma (found version "0.6.7")
-- Configuring incomplete, errors occurred!
See also "/workspaces/cmakeQuickStart/build/CMakeFiles/CMakeOutput.log".
```

Interestingly I do not get that error when I install armadillo using `apt-get` (with the exact same `CMakeLists.txt`).

I would be very thankful if someone is able to explain this. Just to understand that process.

**Comment by RUrlus** [comment]
Ha @BerriJ, your CMake looks a bit off.

You can have a look at the [integration test CMakeLists.txt](https://github.com/RUrlus/carma/blob/stable/integration_test/CMakeLists.txt)
You can follow [this example from the CICD](https://github.com/RUrlus/carma/blob/stable/.github/workflows/install_test.yml) on how to call the CMake script.

Let me know if this does not work for you.

**Comment by RUrlus** [comment]
In your case you would replace the fetch content section with:

```cmake
find_package(pybind11 REQUIRED)
find_package(armadillo REQUIRED) # use this if you want to use the installed version
find_package(carma REQUIRED)
```

Note that when the carma target is created we check if there exists a target `armadillo` if not we create one based on the header only version of Armadillo.

**Comment by BerriJ** [comment]
@RUrlus thank you so much!

I stripped down the [CMakeLists file](https://github.com/BerriJ/carma_boilerplate/blob/main/CMakeLists.txt) to its bones. Using your advice worked like a charm. I committed the changes and will keep the repo alive for future reference.
