### ISSUE TITLE
Weird (?) behavior with arrays, especially with arrays created via `np.ones` 

### ISSUE THREAD

**Issue by simon-hirsch** [RUrlus/carma#126]
Hi, 

this might be a rookie mistake. I don't know a lot about `C++`.
I have the following `C++` / Armadillo Code:
```
namespace my_namespace
{
   static arma::vec return_vec(const arma::vec x) 
      {
          return (x);
      };
}
```
using CARMA / Pybind11 I do:

```
PYBIND11_MODULE(rolch, m)
{
    m.doc() = "pybind11 rolch plugin"; // optional module docstring
    m.def("return_vec", &my_namespace::return_vec, "A function that returns a vector");
}
```
Sometimes, I see the following behaviour:
![image](https://github.com/RUrlus/carma/assets/64348015/0f93a280-86ab-4154-bb01-104c7d9548d4)
 
and the Vector is actually:
![image](https://github.com/RUrlus/carma/assets/64348015/874167e2-6744-4e56-9eff-636de7483b2c)

What might be the reason for that?
I'm not really able to pin the behaviour down. 

I have also noted that this:
![image](https://github.com/RUrlus/carma/assets/64348015/9bc7f3c0-7c63-4d94-af22-e94660600fc4)
_sometimes_ evaluates to `False` but only for the first few elements of the array.

Any help is much appreciated!

**Comment by RUrlus** [comment]
Hi @simon-hirsch, you can't do what you're doing, see [memory safety section](https://carma.readthedocs.io/en/latest/memory_management.html#memory-safety).

What is most-likely happening is that returned vec is pointing to memory that is freed and a part is already being used for something else.

The input argument borrows the memory from the array (this is to allow you avoid copying read-only input arrays).
You should copy out the vector if you want to return it.

The behaviour is not related to `np.ones`

**Comment by simon-hirsch** [comment]
Hi @RUrlus,

thanks for the quick reply!

I'm not sure I get it completely. I thought that in C++, without the "&", I'm already doing a pass-by-copy to the function.

So essentially I'd have to do a 
```
static arma::vec return_vec(const arma::vec x)
{
  arma::vec y = x;
  return (y);
}
```
?

I noted the problem in a more complex context when I was passing sample weights to a function. I don't want to store the weights (per default usually a vector of ones) or need them for anything else, but seemingly I'm getting different results depending on how I pass the weights. 

Or would you advise to do generally explicit pass-by reference with the "&" for values we don't want to store? Does the const declaration within C++ also within CARMA ensure that the original value does not change?

How does CARMA handle the arrays that are created on the fly by users? For example, in a regression setting, if the user does
`OLS(X, y, weights=np.ones(X.shape[0])`, what's the best way to handle this?

Thanks for your help!

**Comment by RUrlus** [comment]
@simon-hirsch I suggest going through the [Design patterns](https://carma.readthedocs.io/en/latest/basic_usage.html#design-patterns) and [examples](https://carma.readthedocs.io/en/latest/examples.html) in the documentation.

If you're copying a container that does not mean you always copy the data of the container.
If you want to have easy control over when it gets copied and when not I suggest using the manual converters rather than the type caster.

If the weights are read-only pass as `const py::array_t<double>&` otherwise `py::array_t<double>&`. If you need to copy use the copy argument of the converter functions.

**Comment by simon-hirsch** [comment]
Hi @RUrlus, I think I understand now why I can't do that `return_vec` thing. 

It seems however that actually two problems were mixed up here: `np.repeat(1, N)` returns an `np.array()` of integers, while `np.ones(N)` returns floats by default. How does CARMA handle automatic conversion of integers?  
It seems to me that with manual copying and borrowing, this is handled well, but with automatic conversion I'm experiencing undefined behavior.

This is with the OLS example:
![image](https://github.com/RUrlus/carma/assets/64348015/c1dd0df1-701d-4b28-821d-47f89b9b60af)
while I've done an implementation with manual conversion:
```
py::tuple example_ols_manual_conversion(py::array_t<double>& X, py::array_t<double>& y) {
    
    arma::Mat<double> X_mat = carma::arr_to_mat<double>(X);
    arma::Col<double> Y_col = carma::arr_to_col<double>(y);
    int n = X_mat.n_rows, k = X_mat.n_cols;

    arma::colvec coeffs = arma::solve(X_mat, Y_col);
    arma::colvec resid = Y_col - X_mat * coeffs;

    double sig2 = arma::as_scalar(arma::trans(resid) * resid / (n-k));
    arma::colvec std_errs = arma::sqrt(sig2 * arma::diagvec( arma::inv(arma::trans(X_mat)*X_mat)) );

    // We take ownership of the memory from the armadillo objects and
    // return to python as a tuple containing two Numpy arrays.
    return py::make_tuple(
        carma::col_to_arr(coeffs),
        carma::col_to_arr(std_errs)
    );
}
```
which does not show this behaviour?
![image](https://github.com/RUrlus/carma/assets/64348015/cd750168-ebd5-44a1-b558-145a699a5242)

**Comment by RUrlus** [comment]
@simon-hirsch good to hear!

Regarding the type conversion from int -> float, this actually handled by Pybind11. By default Pybind does type casting when needed and possible. For the manual bindings you specify `py::array_t<double>&`, seeing no overloads pybind11 casts the array to floats and passes it on.

From the perspective of CARMA this conversion breaks borrowing, as the array on the Python side and the object you're manipulating on the C++ are not the same.

For the type-caster this is slightly more complicated and something might be going wrong there.
The type-caster code only knows that you request a vector with `T = double` and assumes that object can be interpreted as an `py::array_t<double>` specifying the expected type to  pybind11 using:

```C++
PYBIND11_TYPE_CASTER(armaT, _("Numpy.ndarray[") + npy_format_descriptor<T>::name + _("]"));
```

I am not entirely sure what pybind11 does in the background with regard to the type conversion in this case. But I don't know how we could catch this on CARMA's side, nor would I consider type-conversions part of CARMA's responsibility.

To protect against this type of issues you can set `.no_convert()` which should prevent this, [see here for details](https://pybind11.readthedocs.io/en/stable/advanced/functions.html?highlight=no%20convert#non-converting-arguments).

**Comment by simon-hirsch** [comment]
@RUrlus thanks for the explanation. Unfortunately, I'm not really able to get this working straight forward.
For the manual conversion, CARMA and pybind even manage to correctly cast a `np.repeat("1", N)` to floats. 

For the automatic conversion, even if I set the `py::arg("X").noconvert()` in pybind, the automatic casting still seems to converting integers wrongly towards floats.

That's my code:
```
m.def("example_ols", &example_ols, py::arg("X").noconvert(), py::arg("Y").noconvert(), "OLS example");
```
![image](https://github.com/RUrlus/carma/assets/64348015/f4e5771e-7e18-4d5f-937e-4cf57e01b7cc)

The background for this questions is that we'd like to avoid manual pybind / CARMA conversions as much as possible to be able to re-use most of the code easily for `Rcpp` and keep a joint code base for R and python package.

**Comment by RUrlus** [comment]
@simon-hirsch Makes sense regarding Rcpp and this.
Have you tried using the underlying type `arma::Col<double>` rather than the alias? Because I am a bit surprised `noconvert` doesn't seem to have an effect

**Comment by simon-hirsch** [comment]
Hi @RUrlus, just to give a heads-up. I had some stuff coming in between, but I will try it out!
I think we can close this issue, as the original issue is solved/understood.
I'll create a new one once I've tried it and if the issue persists, then I'll add a proper description of no-convert issue and a working example. Thanks!
