### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by conradsnicta** [RUrlus/carma#128]
@RUrlus Could you make a new release of CARMA, say 0.6.8 or even 0.7.0 ?

The last release was about a year ago, and uses Armadillo 11.2.

The current git stable branch uses Armadillo 12.8 as default, which has numerous improvements over 11.2:  
https://arma.sourceforge.net/docs.html#changelog

**Comment by RUrlus** [comment]
hi @conradsnicta, fair point. I'll create a release today or the next

**Comment by RUrlus** [comment]
Done

**Comment by conradsnicta** [comment]
thanks
