### ISSUE TITLE
clangd can't find carma correctly.

### ISSUE THREAD

**Issue by r1cheu** [RUrlus/carma#131]
Hi @RUrlus! Thanks for the great work!　As the title suggests, I'm encountering an issue where clangd is unable to correctly locate carma (even though using carma poses no problems), which is preventing the use of LSP and is quite frustrating.
Attached below are screenshots that provide hints about the issue when I attempt to include carma:
![image](https://github.com/RUrlus/carma/assets/124009368/f31f061f-877d-40f8-97d3-bff4fc16c191)

![image](https://github.com/RUrlus/carma/assets/124009368/a719d1fe-844d-44bf-a048-2619eafd989c)
![image](https://github.com/RUrlus/carma/assets/124009368/72a28a30-e418-49ea-ad37-e1d6e9b86218)

I've also tried including the numpy path in the .clangd configuration file, but unfortunately, this did not resolve the issue.

**Comment by RUrlus** [comment]
Hi @r1cheu, thanks!

Unfortunately carma doesn't do anything special in regard to clangd. This depends entirely on your configuration of clangd where carma is located. I personally use clangd with `compile_commands.json` which I symlink from the build directory in the root directory of the project.

Regarding the last image, that error/warning is expected as you do include armadillo before carma in that particular translation unit.

**Comment by r1cheu** [comment]
> Hi @r1cheu, thanks!
> 
> Unfortunately carma doesn't do anything special in regard to clangd. This depends entirely on your configuration of clangd where carma is located. I personally use clangd with `compile_commands.json` which I symlink from the build directory in the root directory of the project.
> 
> Regarding the last image, that error/warning is expected as you do include armadillo before carma in that particular translation unit.

ok, got it. thanks for your prompt response.
