### ISSUE TITLE
type

### ISSUE THREAD

**Issue by beckerrh** [RUrlus/carma#14]
Hello,

Having tried your nice project, I think there is a type in carma.h on line 320.
I guess it should read  "T" instead of "double".

Thanks a lot for sharing your project, I had tried to do this on my own, but my knowledge on C++ is too limited.

Best regards,
Roland

**Comment by RUrlus** [comment]
Hi Roland,

Sorry for the slow response. Thanks for filing the issue and good spot.
Happy to hear you like it.

Regards,

Ralph
