### ISSUE TITLE
Pybind11 and Armadillo headers as a submodule instead of being embedded

### ISSUE THREAD

**Issue by hpwxf** [RUrlus/carma#24]
Shipping Pybind11 and Armadillo is convenient but increase a lot the size of the repository.
Moreover, since this project is "header only", it could be convenient to embed in other project.

What do you think about using submodule ? (If necessary, I can do it)

**Comment by RUrlus** [comment]
I chose shipping the libs to make the package easily pip installable but happy to move to submodules as they are only used for testing anyway. I am quite busy at the moment so if it's urgent feel free to change, otherwise I'll pick it up later.

**Comment by hpwxf** [comment]
I will do it tomorrow.

**Comment by RUrlus** [comment]
Closed by 369342e90b75b9a703a183c6f328a549d5beec27
