### ISSUE TITLE
Using ctest for launching tests

### ISSUE THREAD

**Issue by hpwxf** [RUrlus/carma#25]
It could be convenient to run tests using `ctest`. 
To do that, it requires to keep generated library in *build* directory (and not to copy them into `tests` directory).
By that way, it would be possible to have *in parallel* several build directories for several configurations (e.g. Debug, StaticAnalysis, Release...)

Again, if it could be a good idea, I can do it.

**Comment by RUrlus** [comment]
Not against it in principle. How does travis handle multiple parallel builds in a single node?
This would involve changing the travis config which is a bit of a mess.
Again, feel free to pick this up, otherwise I'll have a look but that might take a few weeks.

**Comment by hpwxf** [comment]
When I said "parallel build...", it was about "several build directories" with a given configuration for each. This happens in the development process when one wants to compile/test Release and Debug configurations (and in that case, if there are generated files out of build directory they could conflict).

Using "parallel build" in the sense of "compiling several units in parallel", is possible even with a single node (using `-j <n>` option) but the benefit could be low, especially in Travis.
(while compiling a file, file accesses are typically *disk-bound* and if there are also other compilation processes, you should maximize CPU usage).

**Comment by RUrlus** [comment]
For some reason I had a third option in mind where all configs were build in the same travis job in parallel.
Anyway sounds good, happy to learn on how to do it better.
