### ISSUE TITLE
Static Analysis : use after move

### ISSUE THREAD

**Issue by hpwxf** [RUrlus/carma#26]
FYI, using clang static analysis, I found the following possible bug:

(sorry for this dirty image export)

---
<img width="1063" alt="" src="https://user-images.githubusercontent.com/26146722/86006394-2d489600-ba16-11ea-8090-2ca5b0dc9ffd.png">

**Comment by RUrlus** [comment]
You're right, that's a sloppy bug. Closed by 7451f77e952e728c2451aefd15c045ef3edab2d9
