### ISSUE TITLE
MacOS and Windows support

### ISSUE THREAD

**Issue by hpwxf** [RUrlus/carma#28]
I'm working to add support for macOS and Windows (code + CI).

By the way, I suggest reorganizing `.travis-ci.yml` to externalize large part of scripts (with YAML restriction) as external scripts in a `.travis-ci` directory. My idea is to have the workflow in `.travis-ci.yml` with implementation detail in the scripts.
By that way, it is easier to verify locally is the scripts are ok (one can run them even without Travis).

As an example, it should be something like:
```
install:
  # Install dependencies
  - |
    . ${TRAVIS_BUILD_DIR}/.travis-ci/load_env.sh
    ${TRAVIS_BUILD_DIR}/.travis-ci/install.sh
    [[ "$SONAR" = true ]] && ${TRAVIS_BUILD_DIR}/.travis-ci/install_sonar.sh
```

**Comment by RUrlus** [comment]
> I'm working to add support for macOS and Windows (code + CI).

It would be great to get CI coverage for both. Regarding code support, I develop on MacOS, I have not run into any issues with Mojave or Catalina. Windows I have not checked although both pybind11 and armadillo support it.

external travis build scripts sounds great, it's quite a mess in the current state

**Comment by RUrlus** [comment]
In summary CICD support present but disabled for now due to #33

**Comment by hpwxf** [comment]
Good summary 😉

**Comment by hpwxf** [comment]
Since #35 has been merged, Windows support is done.
We can close this issue.
