### ISSUE TITLE
Add coverage report

### ISSUE THREAD

**Issue by hpwxf** [RUrlus/carma#31]
Usually, I use https://coveralls.io (coupled with `lcov`).
It is easy to do from Travis.

To do that, I have to add new `BUILD_MODE`. In that case, I will change `DEBUG` config variable with a `BUILD_MODE` config variable to support values: `Debug`, `Release`, `Coverage`.

**Comment by RUrlus** [comment]
This has been on my todo list for a while. This would require C++ test framework for it to work?

**Comment by RUrlus** [comment]
Fine with coveralls.io, I just linked the repo. Let me know if you need the token.

**Comment by RUrlus** [comment]
Catch2 has been added as a submodule as the C++ testing framework.

I've started writing C++ tests for the conversion, a significant chunk of the armadillo to numpy code has tests, see 4004662665098978ef764945735db888200bbfa5. This story can be picked up after #48 has been closed.

**Comment by hpwxf** [comment]
Very nice!

I will add `lcov` support in CMake and the travis-ci counterpart to commit results into https://coveralls.io.
It could be ok today or tomorrow.

**Comment by RUrlus** [comment]
That would be great thanks, no rush though I need fix a few bugs that only show-up on linux and a memory leak in ArrayStore.

I noticed that the C++ tests are not being picked up by CTest on the [windows run](https://travis-ci.com/github/RUrlus/carma/jobs/368625059), any thoughts on why?

**Comment by hpwxf** [comment]
> I noticed that the C++ tests are not being picked up by CTest on the [windows run](https://travis-ci.com/github/RUrlus/carma/jobs/368625059), any thoughts on why?

I'm trying to understand what happens.
