### ISSUE TITLE
CMake minimal requirement -> 3.7

### ISSUE THREAD

**Issue by hpwxf** [RUrlus/carma#38]
Using https://github.com/nlohmann/cmake_min_version, it appears that the minimal CMake requirement is CMake 3.9 (if we need `DESCRIPTION` field in main `PROJECT` command) or CMake 3.7 if we don't need that description field.

Using the minimal requirement could be useful to be accessible to more users.

PS: this has been tested with CMake config from #35 against all (84) versions of CMake (from 3.1.0 to 3.17.3).
```
# without DESCRIPTION field, `cmake_minimum_required` defaulted to 3.0,  and clang-format installed
venv/bin/python cmake_min_version.py -- -DBUILD_TESTS=on -DBUILD_EXAMPLES=on -DVALGRIND_TEST_WRAPPER=on -DPYBIND11_PYTHON_VERSION=3.7 -DPYBIND11_CPP_STANDARD=-std=c++14 /data
Found 84 CMake binaries from directory tools

[  0%] CMake 3.11.2 ✔ works
[ 12%] CMake 3.6.2  ✘ error
[ 25%] CMake 3.9.2  ✔ works
[ 38%] CMake 3.8.0  ✔ works
[ 57%] CMake 3.7.0  ✔ works
[ 83%] CMake 3.6.3  ✘ error
[100%] Minimal working version: CMake 3.7.0

cmake_minimum_required(VERSION 3.7.0)
```

**Comment by RUrlus** [comment]
Let's move to 3.7, I don't particularly care about the description.
