### ISSUE TITLE
Fix prefix path strip in coveralls.io

### ISSUE THREAD

**Issue by hpwxf** [RUrlus/carma#54]
As you can see in https://coveralls.io/builds/32593847/source?filename=/home/travis/build/RUrlus/carma/include/carma/carma/converters.h

Source code cannot be loaded in coveralls.io. It requires to configure a strip path in coveralls.io.
@RUrlus as you are the owner, you can do that by setting `/home/travis/build/RUrlus/carma` in the config box displayed following the previous link.

**Comment by RUrlus** [comment]
Updated

**Comment by hpwxf** [comment]
I just looked at https://coveralls.io/builds/32783486/source?filename=%2Fhome%2Ftravis%2Fbuild%2FRUrlus%2Fcarma%2Finclude%2Fcarma%2Fcarma%2Fconverters.h
and I saw:
<img width="1117" alt="Capture d’écran 6" src="https://user-images.githubusercontent.com/26146722/90525036-14837380-e16f-11ea-9df8-ab4f70a6da29.png">

@RUrlus Do you have the same error?

**Comment by RUrlus** [comment]
Should be fixed now, safari was adding the exclusion path multiple times
