### ISSUE TITLE
How to install carma

### ISSUE THREAD

**Issue by mizkulg** [RUrlus/carma#65]
I went through the steps here: https://carma.readthedocs.io/en/latest/basic_usage.html to build the system but the last step: To installation carma, you have to define `-DCMAKE_INSTALL_PREFIX=/installation/path/directory`
is not working. Could someone explain a bit more thoroughly what this step entails? I'm just getting:

`zsh: no such file or directory: -DCMAKE_INSTALL_PREFIX=/usr/local`

**Comment by RUrlus** [comment]
I don't understand what you're doing. Can you provide a some details; what is your OS, how are you building it?

**Comment by mizkulg** [comment]
I'm just trying to install carma. I'm using Linux (Debian) and am going through the **Build Systems** part of the docs.

**Comment by RUrlus** [comment]
OK, so I think you are running `-DCMAKE_INSTALL_PREFIX=/usr/local` as an command. It's a definition you need to set to install Carma in the right location.

If you want to install it you run the below in the build directory:
```cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local .. && make install```

Perhaps [this example](https://github.com/smrfeld/speed-up-python-with-carma) will help you.

I'll close the issue for now, please reopen if this doesn't solve your issue

**Comment by mizkulg** [comment]
Thanks. I keep getting the error:

```
In file included from /home/shawn/anaconda3/envs/pybind/lib/python3.7/site-packages/pybind11/include/pybind11/buffer_info.h:12,
                 from /usr/local/include/carma/carma/converters.h:22,
                 from /usr/local/include/carma/carma/arraystore.h:1,
                 from /usr/local/include/carma/carma.h:1,
                 from carma.cpp:3:
/home/shawn/anaconda3/envs/pybind/lib/python3.7/site-packages/pybind11/include/pybind11/detail/common.h:112:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
```

Conda 4.8.2
Python 3.7.3

Pybind11 runs fine on other codes that I have. But with carma the example code at examples/example.cpp gives me the error above. I am running:

`c++ -O3 -Wall -shared -std=c++14 -fPIC -larmadillo`python3.7 -m pybind11 --includes` carma.cpp -o example`python3.7-config --extension-suffix``
