### ISSUE TITLE
invalid conversion from ‘const arma::Mat<double>*’ to ‘arma::Mat<double>*’

### ISSUE THREAD

**Issue by SanPen** [RUrlus/carma#69]
Hi, 

I'm trying to use carma (cloned from master today), and I am getting all sorts of errors related to invalid conversions:

`invalid conversion from ‘const arma::Mat<double>*’ to ‘arma::Mat<double>*’`

In this case the function signature is:

`const arma::vec& getQmaxBus( ) const { //some stuff; }`

Not sure if it helps, but I have been using [this header](https://gitlab.com/sangrey/Arma_Wrapper/-/blob/pybind11_serialization/src/arma_wrapper.cpp) to do the same that I want to use carma for, and at least this sort of conversions worked flawlessly.

BR,
Santiago

**Comment by RUrlus** [comment]
We don't have an overload for const pointer, we have `const lvalue reference`, `lvalue reference` with copy parameter, `rvalue reference` and `pointer`

**Comment by RUrlus** [comment]
I was wrong with regards to the above, those are the overloads on the dev branch. The master doesn't have `const` support at all, nor are you are you requesting a const pointer.

To get the desired behaviour you can copy out the vector for now or convert it and mark the array as non-writeable before returning
