### ISSUE TITLE
Carma versions not set in `include`

### ISSUE THREAD

**Issue by motiwari** [RUrlus/carma#78]
Relevant code: https://github.com/RUrlus/carma/blob/7e4c54fcffedf319fb3f1f66eccb0a3d387400ea/include/carma#L39-L41

If including the `carma` libraries, these lines throw an error because these variables are only set via cmake: https://github.com/RUrlus/carma/blob/7e4c54fcffedf319fb3f1f66eccb0a3d387400ea/CMakeLists.txt#L3-L5

The error is the standard `use of undefined identifier CARMA_VERSION_MAJOR` etc.

Could you provide guidance on how to fix this? Running `cmake` does not fix the issue

**Comment by RUrlus** [comment]
Hi @motiwari, you're right it wasn't being set unless you installed the headers using CMake or used the CMake target.
Release v0.5.1 (02a2859c19c9735872475c1ef719dea37a9ecfe2) contains a fix for this.

Note, if you are not building through CMake you have to include `carma` before `armadillo`. When using the CMake build you don't have this issue.
