### ISSUE TITLE
Question about library installation + finding carma

### ISSUE THREAD

**Issue by peekxc** [RUrlus/carma#81]
On one hand, like arma and pybind11, CARMA is (mostly) header-only. On the other hand, CARMA isn't completely header-only. Compiling any source file after adding the `include` directory relative to some submodule-or-cloned version of CARMA results in a message like: 

```...failed to find header file config.h```

This isn't surprising, as the file named `config.h.in` contains cmake-specific installation info that once compiled yields the generated `config.h`.

However, this makes including carma in another project a little cumbersome. For example, this essentially ties the inclusion of carma in a project to cmake-dependent builds if one assumes carma isn't installed already. For python packages, this may involve invoking cmake via setup.py to explicitly generate to `_deps` folder with the corresponding includes. In contrast, I found it easier to just configure and install carma to my system library path, then just include it directly using e.g. [meson](https://mesonbuild.com/index.html).

I have two questions regarding this: 
    
1) Is there a way to make carma truly header-only? For example, by using some default configuration for the compile-time variables (e.g. `ARMA_ALIEN_MEM_ALLOC`) and configuring a "default" `config.h`? I apologize if it may be more complicated than that. 

2) armadillo can be easily incorporated into other cross-platform build systems, presumably through the use of pkgconfig files, e.g. in meson one can simply do

```python
arma = dependency('armadillo', version : '>=10.5.2', required : true)
executable('foo', 'foo.cc', dependencies : [arma])
```
or in cmake, 

```cmake
find_package(Armadillo 10.5.2 REQUIRED)
include_directories(${ARMADILLO_INCLUDE_DIRS})
add_executable(foo foo.cc)
target_link_libraries(foo ${ARMADILLO_LIBRARIES})
```

is there an equivalent for CARMA?

**Comment by RUrlus** [comment]
Hi @peekxc, 

Yes CARMA is currently tied to CMake, however, you could install it your system library using CMake, which will create a default `config.h`, and then use your preferred build system:

```bash
cmake ..
cmake --build . --target install
```

A downside of this approach is that you will need to make sure that CARMA is always included before Armadillo.
There is no easy way around this, `ARMA_ALIEN_MEM_*` need to be set before including Armadillo.  The CMake target handles by pre-compiling the required header. Hence, the recommendation to use the CMake build.

Regarding Python, I would advise to ship CARMA in the tar and use something like [ci-buildwheels](https://github.com/pypa/cibuildwheel) to create wheels for the various platforms. Pybind11 documentation has various examples on how to integrate CMake build in `setup.py`

CARMA is currently missing the required files for `find_package` but I will pick that up.

I am open to a PR for pkgconfig or something similar

**Comment by RUrlus** [comment]
@peekxc I had a look today and I see some ways to improve usability.
I included a default `config.h` so it header-only independent of CMake.

I am working on a better CMake installation and targets, provide it as a pip package like Pybind11.
I am not familiar with pkgconfig but if it's not too much work I'll include that as well.

**Comment by peekxc** [comment]
Hi @RUrlus. Thanks for looking into this. A pip-installeable version would definitely be ideal, if possible.

That being said, I actually had not heard of ci-buildwheels and did not consider the use of CI's to automate package (wheel) building and distribution. Thanks for the tip!
