### ISSUE TITLE
Exception handling broken when linking to carma for Windows+Clang

### ISSUE THREAD

**Issue by kjohnsen** [RUrlus/carma#92]
I've got another bug for you! Thankfully it occurred to me this time to test whether carma could be responsible even though it didn't seem like it. 

Whereas pybind11 is supposed to turn a C++ exception into a RuntimeError in Python, my program was crashing upon encountering `std::runtime_error`. Linking to carma turned out to make the difference, even though it isn't used at all, not even included. 

[Here is an MRE](https://github.com/kjohnsen/carma-exceptions-bug). I only get the bug on Windows; a WSL build works fine for me.

**Comment by RUrlus** [comment]
Hi @kjohnsen, unfortunately I can't reproduce the issue with your MRE. I don't have access to a Windows machine so I created an action based on your [MRE](https://github.com/RUrlus/carma/tree/stable/mre) for all platforms, see [here](https://github.com/RUrlus/carma/actions/runs/1262326922). However, the test passes for both the stable and the unstable branch

**Comment by kjohnsen** [comment]
@RUrlus I just cloned your MRE and found that the bug happens for Clang (11), but not for MSVC. I might have misled you by saying the compiler was "MSVC Clang" which I said because it was Clang as installed through Visual Studio, with the MSVC-like interface

**Comment by RUrlus** [comment]
Same story for [Clang-12](https://github.com/RUrlus/carma/runs/3678315346?check_suite_focus=true#logs) on actions, can't replicate it unfortunately.

**Comment by kjohnsen** [comment]
Okay, so I upgraded to Clang 12 on my local computer and the bug is still there for me, and again only on Clang. Any ideas?

**Comment by RUrlus** [comment]
Can you post a dump of the crash? I wouldn't know what carma could be doing when you link but don't include it, other than a standard issue. Carma targets are std14 minimum. What standard are you using?

**Comment by kjohnsen** [comment]
A dump as in the arma/carma debug statements? I'll get those in a sec. Definitely C++14. I set it explicity in the CMakeLists.txt just now though just in case

[configure.txt](https://github.com/RUrlus/carma/files/7213406/configure.txt)

**Comment by kjohnsen** [comment]
I have nothing else to share, really, other than the fact that it's the same `Windows fatal exception: code 0xc0000374`. No Armadillo or carma debug statements come up since neither is even included. 

To be clear, I'm using the exact same MRE you used with GitHub actions, except now it specifies C++14 and adds the debug compile definitions. All I have to do is comment out `TARGET_LINK_LIBRARIES(pymod PUBLIC carma::carma)` and it works.

**Comment by RUrlus** [comment]
You don't get a crash report or stacktrace alongside the fatal exception? Because based on this I have no idea what could be causing this. You are the first to report this issue and I can't reproduce it in actions.

**Comment by kjohnsen** [comment]
I was going to send a screenshot of the debug thread stack (no stack trace is printed on crashing), but as I just tried compiling the MRE using the unstable branch (which has the fresh fix of the other bug), this bug is fixed! The error is raised to Python correctly.

Though it's fixed in the MRE, for some reason it's still in my codebase. I'll let you know if I can't get it ironed out.

**Comment by kjohnsen** [comment]
Well, I can't get rid of it. It magically went away for a few minutes but came back next time I built. I'm baffled. I switched from Clang 12 to MSVC and this bug went away, but other memory bugs started popping back up. I appreciate all the help, but as much as I'd love to get everything working right on Windows, I think I'm just going to switch to Linux for this project.
