### ISSUE TITLE
Repo does not pass flake8

### ISSUE THREAD

**Issue by motiwari** [RUrlus/carma#96]
Hi, thanks again for making this repo.

Running the following command from the top-level directory of the repository:

`flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics`

returns a lot of bugs

**Comment by motiwari** [comment]
Similarly for `cpplint`:

`cpplint --recursive .`

surfaces lots of style errors, the majority of which can be `codemod`ded away

**Comment by RUrlus** [comment]
Hi @motiwari, the C++ code is checked with cpplint and there is a clang-tidy target for formatting.
I don't agree with the code-style suggestions that `cpplint` gives on the files in the include directory with the exception of the copyright ones which I've changed.

Regarding Python the vast majority of issues are coming from external libraries when I run it. We only use Python in the tests, for which I've fixed the few style issues. See 75057dddb7d6f7422db70a5d937709e10fb25dc5
